# Generated by Django 4.0.4 on 2022-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('source_file', models.FileField(upload_to='source_files')),
            ],
        ),
    ]
