# Generated by Django 4.0.4 on 2022-05-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryFile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('secondary_file_name', models.CharField(blank=True, max_length=255)),
                ('secondary_file', models.FileField(upload_to='source_files')),
            ],
        ),
    ]
