# Generated by Django 4.0.4 on 2022-05-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_bot', '0002_secondaryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryfile',
            name='secondary_file',
            field=models.FileField(upload_to='destination_files'),
        ),
    ]
